### ISSUE TITLE
Option to specify single or double quotes in output

### ISSUE THREAD

**Issue by pdehaan** [neagle/grunt-sass-directory-import#2]
It'd be nice to have a Grunt option to specify whether you want to use `@import 'foo';` (single quotes) or `@import "foo";` (double quotes).
We use [**scss-lint**](https://github.com/causes/scss-lint) Ruby Gem and it'd be nice to be able to tweak the generated output without having to override rules for specific files.

```sh
$ scss-lint app/styles/

app/styles/modules/_all.scss:5 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:6 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:7 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:8 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:9 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:10 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:11 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:12 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:13 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:14 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:15 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:16 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:17 [W] StringQuotes: Prefer single quoted strings
app/styles/modules/_all.scss:17 [W] FinalNewline: Files should end with a trailing newline
```

**Comment by neagle** [comment]
That seems like a reasonable request, though this is still going to leave a problem in your linter, since the `_all.scss` doesn't end with a trailing newline. (Which I just noticed. I can add that, too.)

Keep in mind you should be able to remove `_all.scss` from your linting via a globbed exception, which would be a better solution, ultimately, since getting someone else (me!) to change generated code is more of a hassle than updating your own code. ;)

**Comment by neagle** [comment]
I went ahead and pushed one more change: the plugin now adds empty newlines at the end of generates files. That should take care of your other scss lint problem, and it's a good practice anyway.
